  exports.jobCategories = [
    'Trgovina i prodaja',
    'Ugostiteljstvo',
    'Kuhinja i priprema hrane',
    'Administracija',
    'Čuvanje i nega dece i odraslih',
    'Proizvodnja',
    'Fizički poslovi',
    'Higijena',
    'Nega i lepota',
    'Majstori',
    'Građevinstvo',
    'Prevoz i dostava',
    'Skladištenje i logistika',
    'Marketing i promocija',
    'Turizam',
    'Poljoprivreda',
    'Medicina i farmacija',
    'Bezbednost i zaštita',
    'IT',
    'Ostali poslovi',
    'Auto-moto',
    'Bela tehnika i elektronika',
    'Čuvanje i nega dece i odraslih',
    'Građevinarstvo',
    'Nega i lepota',
    'Zdravstvo',
    'Transport',
    'Podučavanje',
    'Umetnost',
    'Servis i popravka',
    'Odmor i putovanja',
    'Audio, TV i video',
    'Kuća i dvorište',
    'Poslovanje',
    'Mehanizacija',
    'Majstorske',
    'Muzika i instrumenti',
    'Kompjuteri i konzole',
    'Sport i rekreacija',
    'Dogadjaji i izlasci',
    'Kućni ljubimci',
    'Zanati',
    'Razno',
  ];